fail_fast: true
repos:
- repo: local
  hooks:
    - id: black
      name: black
      entry: poetry run black
      language: system
      types: [file, python]
    - id: isort
      name: isort
      entry: poetry run isort
      language: system
      types: [file, python]
    - id: pytest
      name: pytest
      entry: poetry run pytest
      language: system
      types: [python]
      pass_filenames: false
      always_run: true